### ISSUE TITLE
Version 1.0 todo

### ISSUE THREAD

**Issue by James-Frowen** [MirrorNetworking/SimpleWebTransport#1]
**Main**
- [x] c# server
- [x] wegbl client
- [x] SSL
- [x] C# client
- [x] Reduce allocations 

--- 

**Improvements**
*these arn't required but could be nice to have*
- [ ] Handle Ping/Pong
- [ ] Close connect message (including reason)
- [ ] reply with 400 bad request for handshake header 

see [this](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers) for info on ping/pong + close

--- 

**Bonus**
- [x] CI for tests
- [x] CI for release versions

---

**Docs**
- [x] https://mirror-networking.com/docs/Articles/Transports/WebSockets.html
- [x] Readme
- [x] How to set up ssl
- [ ] How to do webgl build (general mirror guide)
- [ ] check for other references to old websocket transport
